apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-secondary
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: secondary
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: secondary
        tier: backend
    spec:
      containers:
      - name: secondary
        image: gcr.io/google_samples/gb-redisslave:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-secondary
  labels:
    app: redis
    role: secondary
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: secondary
    tier: backend